# Case Study: Predicting Virus Contraction with a Artifical Neural Net 

Summarizing an Artificial Neural Network:
1. Take inputs
2. Add bias (if required)
3. Assign random weights to input features
4. Run the code for training.
5. Find the error in prediction.
6. Update the weight by gradient descent algorithm.
7. Repeat the training phase with updated weights.
8. Make predictions.

![](data_1.png)
![](perceptron.png)

In [1]:
# Import required libraries :
import numpy as np

In [2]:
# Define input features :
input_features = np.array([[1,0,0,1],[1,0,0,0],[0,0,1,1],
 [0,1,0,0],[1,1,0,0],[0,0,1,1],
 [0,0,0,1],[0,0,1,0]])
print (input_features.shape)
print (input_features)

(8, 4)
[[1 0 0 1]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 1 0]]


In [3]:
# Define target output :
target_output = np.array([[1,1,0,0,1,1,0,0]])


# Reshaping our target output into vector :
target_output = target_output.reshape(8,1)
print(target_output.shape)
print (target_output)

(8, 1)
[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]


In [4]:

# Define weights :
weights = np.array([[0.1],[0.2],[0.3],[0.4]])
print(weights.shape)
print (weights)

(4, 1)
[[0.1]
 [0.2]
 [0.3]
 [0.4]]


In [5]:
# Bias weight :
bias = 0.3
# Learning Rate :
lr = 0.05

In [6]:
# Sigmoid function :
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [7]:
# Derivative of sigmoid function :
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [8]:
# Main logic for neural network :
# Running our code 10000 times :

for epoch in range(10000):
 inputs = input_features
 #Feedforward input :
 pred_in = np.dot(inputs, weights) + bias
    
 #Feedforward output :
 pred_out = sigmoid(pred_in)
 
 #Backpropogation 
 #Calculating error
 error = pred_out-target_output
 
 #Going with the formula :
 x = error.sum()
 print(x)
 
 #Calculating derivative :
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 #Multiplying individual derivatives :
 z_delta = dcost_dpred * dpred_dz

 #Multiplying with the 3rd individual derivative :
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)
 
 #Updating the bias weight value :
 for i in z_delta:
    bias -= lr * i



1.3327390143216857
1.2979209778166676
1.2637464791833575
1.2302314779296857
1.1973898244294374
1.1652332872165156
1.1337715936399362
1.1030124826189658
1.072961768154447
1.0436234122025332
1.0149996054985957
0.9870908549290709
0.959896076084018
0.9334126896795023
0.9076367206126906
0.8825628984999301
0.8581847586453841
0.8344947424916052
0.8114842967105611
0.7891439702014936
0.767463508368059
0.7464319441497487
0.7260376853799335
0.7062685981339404
0.6871120858145194
0.6685551637983617
0.6505845295357733
0.6331866280561349
0.6163477128845363
0.6000539024203136
0.5842912318664504
0.5690457008305141
0.5543033167434399
0.5400501342626367
0.5262722908411533
0.5129560386555375
0.5000877730921107
0.4876540579951799
0.47564164788168894
0.4640375073254255
0.45282882771055555
0.4420030415493129
0.4315478345524627
0.4214511556339471
0.41170122502322526
0.4022865406503435
0.3931958829600313
0.3844183183021753
0.3759432010370365
0.36776017448468734
0.3598591708393831
0.3522304101610735
0.344864398

0.08300575787735276
0.08295114215719679
0.08289662362277578
0.08284220174112633
0.08278787598446152
0.0827336458301079
0.082679510760443
0.08262547026283906
0.08257152382960076
0.08251767095790918
0.08246391114976287
0.08241024391192192
0.08235666875585107
0.08230318519766466
0.08224979275807143
0.08219649096232085
0.08214327934015148
0.08209015742573555
0.08203712475762637
0.08198418087871229
0.08193132533615999
0.08187855768136876
0.08182587746991848
0.08177328426152175
0.08172077761997609
0.08166835711311604
0.08161602231276688
0.08156377279469618
0.08151160813857172
0.08145952792791211
0.08140753175004678
0.08135561919606671
0.08130378986078568
0.08125204334269465
0.08120037924392048
0.08114879717018347
0.08109729673075694
0.08104587753842507
0.08099453920944355
0.08094328136349926
0.08089210362367238
0.08084100561639573
0.08078998697141748
0.08073904732176251
0.08068818630369717
0.08063740355669025
0.08058669872337632
0.08053607144952324
0.08048552138399145
0.08043504817870262
0.0

0.05963136762635923
0.05960247506095667
0.05957360511893606
0.059544757771792134
0.05951593299108604
0.05948713074844786
0.05945835101557373
0.05942959376422691
0.05940085896623615
0.05937214659349854
0.05934345661797347
0.05931478901169007
0.05928614374673957
0.05925752079528118
0.0592289201295369
0.05920034172179589
0.059171785544408495
0.05914325156979172
0.05911473977042525
0.05908625011885327
0.05905778258768274
0.05902933714958375
0.05900091377729072
0.05897251244359919
0.05894413312136837
0.05891577578351803
0.05888744040303173
0.05885912695295448
0.05883083540639267
0.05880256573651366
0.05877431791654597
0.05874609191977809
0.05871788771956227
0.05868970528930745
0.05866154460248535
0.0586334056326262
0.05860528835332124
0.058577192738218486
0.05854911876102842
0.05852106639551963
0.058493035615517774
0.05846502639490897
0.05843703870763761
0.05840907252770633
0.05838112782917482
0.05835320458616072
0.05832530277283959
0.058297422363443874
0.05826956333226452
0.058241725653647

0.04324956475914038
0.04323217403764201
0.04321479437656672
0.0431974257666875
0.04318006819878978
0.04316272166366719
0.0431453861521221
0.04312806165496874
0.043110748163031676
0.04309344566714357
0.04307615415814786
0.04305887362689892
0.04304160406425983
0.043024345461102564
0.043007097808312744
0.04298986109677988
0.04297263531740991
0.0429554204611135
0.042938216518812966
0.04292102348144067
0.04290384133993874
0.04288667008525887
0.04286950970836162
0.04285236020021821
0.04283522155181013
0.04281809375412693
0.042800976798169243
0.042783870674946045
0.04276677537547613
0.04274969089079067
0.042732617211926505
0.04271555432993257
0.042698502235866465
0.042681460920794945
0.04266443037579426
0.04264741059195204
0.04263040156036407
0.04261340327213442
0.04259641571837958
0.04257943889022353
0.04256247277879904
0.04254551737524975
0.04252857267072918
0.0425116386563979
0.042494715323428134
0.04247780266300105
0.04246090066630631
0.04244400932454251
0.04242712862892001
0.042410258570

0.03259630399958302
0.03258526231778358
0.0325742267444184
0.03256319727504653
0.03255217390523324
0.032541156630544965
0.03253014544655325
0.03251914034883441
0.03250814133296831
0.03249714839453771
0.03248616152912975
0.03247518073233607
0.03246420599975125
0.03245323732697308
0.03244227470960592
0.03243131814325545
0.03242036762353262
0.03240942314605011
0.032398484706426534
0.032387552300284506
0.032376625923249525
0.0323657055709497
0.0323547912390193
0.0323438829230957
0.032332980618819396
0.032322084321835476
0.03231119402779198
0.03230030973234155
0.032289431431140214
0.03227855911984784
0.032267692794128
0.03225683244964889
0.032245978082081406
0.03223512968709985
0.03222428726038351
0.032213450797615506
0.03220262029448212
0.032191795746672525
0.03218097714988172
0.03217016449980614
0.032159357792147514
0.03214855702261149
0.03213776218690689
0.03212697328074532
0.03211619029984475
0.03210541323992411
0.03209464209670709
0.03208387686592218
0.03207311754329906
0.0320623641245

0.02489886408568881
0.02489180243820066
0.024884744164799077
0.0248776892633219
0.02487063773160675
0.02486358956749496
0.02485654476882798
0.024849503333449485
0.024842465259204916
0.02483543054394155
0.024828399185508443
0.024821371181755203
0.024814346530534714
0.02480732522970064
0.024800307277108358
0.02479329267061564
0.024786281408080868
0.024779273487363307
0.02477226890632711
0.024765267662835544
0.024758269754753426
0.024751275179948795
0.024744283936290523
0.02473729602164837
0.024730311433895424
0.024723330170904945
0.02471635223055252
0.024709377610715677
0.024702406309272507
0.024695438324104146
0.02468847365309257
0.024681512294122077
0.02467455424507753
0.02466759950384606
0.02466064806831758
0.02465369993638067
0.02464675510592823
0.02463981357485323
0.024632875341051852
0.02462594040242122
0.02461900875685913
0.0246120804022662
0.02460515533654395
0.024598233557596938
0.02459131506332879
0.024584399851647454
0.024577487920461438
0.024570579267679526
0.0245636738912148

0.02046882634496272
0.020463767467567506
0.020458710739979624
0.020453656160954847
0.020448603729251558
0.020443553443628915
0.020438505302846632
0.020433459305664425
0.02042841545084323
0.02042337373714931
0.020418334163341767
0.02041329672818698
0.02040826143044938
0.020403228268894236
0.020398197242288862
0.020393168349401303
0.020388141589000097
0.020383116959854064
0.020378094460733243
0.020373074090410892
0.020368055847657718
0.020363039731245258
0.02035802573994988
0.020353013872545123
0.020348004127805686
0.020342996504508548
0.020337991001433187
0.020332987617356024
0.02032798635105637
0.020322987201312703
0.020317990166908162
0.020312995246623666
0.02030800243924269
0.020303011743545374
0.020298023158319467
0.020293036682348553
0.020288052314418048
0.020283070053315366
0.020278089897830143
0.02027311184674918
0.02026813589886245
0.020263162052959083
0.020258190307830604
0.020253220662269922
0.02024825311507039
0.020243287665024312
0.020238324310927647
0.02023336305157475
0.02

0.01759106372492486
0.017587172664097428
0.017583283104882497
0.01757939504648398
0.017575508488106295
0.017571623428955574
0.01756773986823751
0.01756385780515729
0.01755997723892211
0.017556098168739598
0.01755222059381739
0.017548344513362124
0.01754446992658565
0.017540596832694655
0.01753672523090044
0.01753285512041225
0.017528986500441268
0.01752511937020035
0.01752125372889818
0.01751738957575094
0.017513526909969268
0.017509665730768342
0.017505806037361404
0.017501947828962527
0.017498091104786284
0.017494235864050856
0.01749038210596976
0.017486529829760455
0.01748267903464007
0.01747882971982545
0.017474981884536556
0.017471135527990178
0.017467290649407552
0.017463447248005304
0.017459605323004834
0.017455764873628044
0.0174519258990965
0.01744808839863088
0.017444252371453528
0.017440417816787623
0.017436584733855676
0.017432753121881306
0.017428922980089523
0.017425094307705835
0.017421267103953753
0.01741744136806156
0.01741361709925271
0.017409794296756098
0.0174059729

0.015509684991988237
0.015506565415001838
0.01550344694528738
0.015500329582300132
0.015497213325497694
0.015494098174336834
0.015490984128276208
0.015487871186771085
0.015484759349281063
0.015481648615264965
0.015478538984180168
0.015475430455486383
0.015472323028641877
0.015469216703106303
0.015466111478341316
0.015463007353806957
0.015459904328961938
0.015456802403268799
0.015453701576188972
0.015450601847182333
0.01544750321571342
0.01544440568124339
0.015441309243234114
0.01543821390114919
0.015435119654453267
0.015432026502607887
0.015428934445078812
0.01542584348132875
0.015422753610822793
0.015419664833027202
0.015416577147404797
0.01541349055342367
0.015410405050547082
0.015407320638243405
0.015404237315979619
0.015401155083220264
0.015398073939436319
0.015394993884091879
0.015391914916656257
0.015388837036595993
0.015385760243381508
0.015382684536481617
0.015379609915365411
0.015376536379500982
0.015373463928360531
0.015370392561412594
0.015367322278128481
0.01536425307797828

0.013678002365970887
0.013675506353496791
0.013673011153514159
0.013670516765656948
0.013668023189555234
0.01366553042484231
0.013663038471151578
0.013660547328113448
0.013658056995362544
0.013655567472530106
0.013653078759250203
0.01365059085515763
0.01364810375988268
0.013645617473062643
0.013643131994328539
0.01364064732331588
0.01363816345965796
0.013635680402991068
0.013633198152950665
0.013630716709169766
0.013628236071284994
0.013625756238931974
0.013623277211745166
0.013620798989361471
0.013618321571415903
0.013615844957545586
0.013613369147386534
0.013610894140575591
0.013608419936750937
0.013605946535548252
0.01360347393660466
0.013601002139559781
0.013598531144048354
0.013596060949710498
0.013593591556183116
0.01359112296310555
0.013588655170115982
0.013586188176853697
0.013583721982958319
0.013581256588066748
0.013578791991819494
0.013576328193856457
0.01357386519381637
0.013571402991341186
0.013568941586069805
0.013566480977642459
0.01356402116570038
0.013561562149885353
0

0.012058533132886073
0.0120565419564308
0.012054551372520428
0.012052561380908322
0.012050571981347735
0.012048583173590421
0.012046594957391299
0.012044607332503399
0.012042620298678142
0.012040633855671612
0.012038648003237062
0.012036662741129411
0.012034678069100357
0.012032693986905485
0.012030710494299879
0.01202872759103707
0.01202674527687142
0.012024763551558681
0.01202278241485516
0.01202080186651261
0.012018821906287003
0.012016842533934424
0.01201486374920846
0.012012885551867358
0.012010907941665483
0.012008930918358418
0.012006954481701693
0.012004978631453445
0.012003003367366594
0.012001028689200166
0.011999054596709802
0.01199708108965064
0.011995108167780988
0.011993135830858148
0.011991164078637873
0.011989192910876745
0.011987222327333513
0.01198525232776404
0.011983282911926518
0.011981314079577476
0.011979345830477162
0.01197737816438027
0.011975411081045162
0.011973444580232417
0.011971478661697399
0.011969513325200853
0.011967548570500253
0.011965584397355233
0.

0.010787027079279254
0.010785399605866941
0.010783772578780493
0.01078214599784777
0.010780519862896798
0.010778894173755604
0.01077726893025116
0.010775644132211881
0.010774019779465627
0.01077239587183959
0.01077077240916291
0.010769149391264166
0.010767526817970385
0.010765904689110983
0.010764283004516872
0.010762661764013415
0.010761040967429858
0.010759420614594839
0.010757800705337939
0.010756181239487517
0.010754562216874097
0.010752943637324042
0.01075132550066904
0.010749707806737563
0.010748090555358858
0.010746473746361618
0.0107448573795767
0.010743241454832853
0.010741625971960822
0.010740010930790023
0.010738396331150035
0.010736782172870607
0.01073516845578154
0.010733555179713195
0.010731942344494871
0.010730329949958928
0.010728717995934611
0.010727106482252002
0.010725495408743124
0.010723884775237447
0.01072227458156605
0.010720664827558346
0.010719055513047082
0.010717446637862116
0.01071583820183386
0.010714230204795838
0.010712622646577519
0.010711015527008816
0.

0.0098504052817176
0.009849026283985207
0.00984764763951651
0.009846269348184833
0.009844891409860668
0.009843513824418615
0.009842136591729167
0.009840759711663316
0.009839383184096218
0.00983800700889742
0.009836631185941969
0.009835255715100522
0.009833880596247124
0.009832505829253713
0.00983113141399189
0.009829757350334534
0.009828383638157134
0.009827010277329185
0.009825637267726117
0.009824264609219147
0.00982289230168265
0.009821520344988233
0.009820148739010992
0.009818777483621699
0.009817406578694121
0.009816036024103914
0.00981466581972279
0.00981329596542374
0.0098119264610807
0.009810557306566381
0.009809188501756327
0.00980782004652292
0.009806451940740701
0.009805084184282942
0.00980371677702263
0.009802349718834535
0.009800983009592867
0.009799616649170617
0.009798250637443995
0.009796884974284159
0.009795519659567709
0.009794154693167745
0.009792790074958424
0.009791425804814236
0.009790061882610723
0.009788698308221488
0.009787335081521409
0.009785972202384752
0.00

0.009065593408606465
0.009064409322756928
0.00906322552157468
0.009062042004963689
0.00906085877282603
0.009059675825063729
0.009058493161580916
0.009057310782280337
0.009056128687065346
0.009054946875838965
0.00905376534850405
0.0090525841049649
0.009051403145123427
0.009050222468883762
0.009049042076148428
0.009047861966820947
0.009046682140804174
0.009045502598002297
0.009044323338321059
0.009043144361660593
0.00904196566792509
0.009040787257019733
0.009039609128847603
0.00903843128331111
0.00903725372031583
0.009036076439764451
0.00903489944156255
0.009033722725611537
0.009032546291817656
0.00903137014008365
0.009030194270313263
0.009029018682410517
0.009027843376279876
0.009026668351824918
0.009025493608951385
0.0090243191475608
0.009023144967560126
0.009021971068851553
0.009020797451340157
0.009019624114931957
0.00901845105952953
0.009017278285038566
0.009016105791362139
0.009014933578405215
0.009013761646074536
0.009012589994272957
0.009011418622904332
0.00901024753187446
0.0090

0.008416433386405742
0.008415401015352708
0.008414368878557066
0.008413336975945429
0.008412305307440193
0.008411273872966973
0.008410242672448887
0.00840921170581116
0.00840818097297874
0.00840715047387569
0.008406120208426515
0.008405090176556551
0.008404060378188583
0.008403030813248002
0.008402001481660482
0.00840097238334958
0.00839994351824025
0.008398914886259101
0.008397886487327921
0.00839685832137349
0.008395830388320757
0.008394802688092173
0.008393775220616961
0.008392747985815241
0.008391720983614959
0.00839069421394123
0.008389667676718504
0.008388641371872174
0.008387615299325801
0.008386589459005112
0.008385563850837274
0.00838453847474524
0.008383513330655401
0.008382488418494094
0.008381463738183992
0.00838043928965182
0.008379415072822194
0.008378391087621895
0.008377367333974484
0.008376343811806741
0.00837532052104456
0.008374297461612445
0.00837327463343529
0.008372252036439709
0.00837122967055176
0.008370207535696339
0.00836918563179928
0.008368163958787145
0.008

# Making predictions:


 a. A tested person is positive for the virus.

In [9]:
#
#Taking inputs :
single_point = np.array([1,0,0,1])#1st step :
result1 = np.dot(single_point, weights) + bias#2nd step :
result2 = sigmoid(result1)
#Print final result
print(result2)



[0.99915866]


b. A tested person is negative for the virus.

In [10]:
#Taking inputs :
single_point = np.array([0,0,1,0])#1st step :
result1 = np.dot(single_point, weights) + bias#2nd step :
result2 = sigmoid(result1)#Print final result
print(result2)



[0.04297448]


c. A tested person is positive for the virus.


In [11]:
#Taking inputs :
single_point = np.array([1,0,1,0])#1st step :
result1 = np.dot(single_point, weights) + bias#2nd step :
result2 = sigmoid(result1)#Print final result
print(result2)

[0.99914219]


In [12]:

#Printing final weights: 
print (weights)
print ("\n\n")
print (bias)



[[10.1634992 ]
 [ 0.45744949]
 [ 2.97441782]
 [ 2.9938138 ]]



[-6.07764153]


## Inference :
In this example, we can notice that 
- the input feature “loss of smell” influences the output the most. If it is true, then in most of the case, the person tests positive for the virus. We can also derive this conclusion from the weight values. 
- Keep in mind that the higher the value of the weight, the more the influence on the output. 
- The input feature “Weight loss” is not affecting the output much, so we can rule it out while we are making predictions for a larger dataset.

Reference :
    
    1. Shukla, et al., “Neural Networks from Scratch with Python Code and Math in Detail — I”, Towards AI, 2020
